### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by nomanmajeed** [binish47/software-construction-lab-Assignment-2#2]
#include <iostream>
#include <stdio.h>
#include <string>
#include <conio.h>
#include<iomanip>
using namespace std;

//structure
struct student{
	//structure members
	string id;
	string first_name;
	string second_name;
	string gender;
	string dob;
	string address;
	string city;
	string phone;
	string program;
	string year;
};
//prototypes
void add(student* s, int n, int index);
void update(student* s, int n, int index);
void Delete(student* s, int n, int index);
void display(student* s, int n, int index);
void displayYear(student* s, int n, int index);
void search(student* s, int n, int index);
void calculate(student* s, int n, int index);

	//global variables
	int n=4;
	struct student* s=new student[n];
	int i, option, index=0;
	float total=0;

//main function
int main(){
	
	s[0].id="12";
	s[0].first_name="Noman";
	s[0].second_name="Majeed";
	s[0].gender="M";
	s[0].dob="12-11-1995";
	s[0].address="H#1";
	s[0].city="RWP";
	s[0].phone="1234";
	s[0].program="BSSE";
	s[0].year="2017";
	index+=1;//index increment
	s[1].id="13";
	s[1].first_name="Adeel";
	s[1].second_name="Fayyaz";
	s[1].gender="M";
	s[1].dob="11-12-1998";
	s[1].address="H#2";
	s[1].city="ISL";
	s[1].phone="9876";
	s[1].program="BSCS";
	s[1].year="2016";
	index+=1;//index increment
	s[2].id="14";
	s[2].first_name="Ahmad";
	s[2].second_name="Qazi";
	s[2].gender="M";
	s[2].dob="26-12-1996";
	s[2].address="H#3";
	s[2].city="RWP";
	s[2].phone="4567";
	s[2].program="BSEE";
	s[2].year="2016";
	index+=1;//index increment
	s[3].id="15";
	s[3].first_name="Shafaq";
	s[3].second_name="Malik";
	s[3].gender="F";
	s[3].dob="01-01-1995";
	s[3].address="H#4";
	s[3].city="ISl";
	s[3].phone="6789";
	s[3].program="BBA";
	s[3].year="2015";
	index+=1;//index increment
	cout<<"Welcome to Student Registration System CIIT, Islamabad"<<endl;
	cout<<" "<<endl;
	while(1){
		cout<<"\nSelect 1 to Add new Student"<<endl;
		cout<<"Select 2 to Update Student Record"<<endl;
		cout<<"Select 3 to Delete Student Record"<<endl;
		cout<<"Select 4 to Display All Students Record on basis of Program"<<endl;
		cout<<"Select 5 to Display All Students Record on basis of Year"<<endl;
		cout<<"Select 6 to Search a Student Record"<<endl;
		cout<<"Select 7 to Calculate Memory Required to Store Data of Each student"<<endl;
		
		cout<<"Enter Option:"<<endl;
		cin>>option;
		if(option==1){
			add(s,n,index);	
		}
		else if(option==2){
			update(s,n,index);	
		}
		else if(option==3){
			Delete(s,n,index);
		}
		else if(option==4){
			display(s,n,index);
		}
		else if(option==5){
			displayYear(s,n,index);
		}
		else if(option==6){
			search(s,n,index);
		}
		else if(option==7){
			calculate(s,n,index);
		}
	}
}
//function to add new student
void add(student* s, int n, int index){
		cout<<"\nSelect 1 to Add new Student at Begining"<<endl;
		cout<<"Select 2 to Add new Student at End"<<endl;
		cout<<"Enter Option:"<<endl;
		cin>>option;
		
		if(option==1){
			if(index==n){
				n=n*2;
				student *temp=new student[n];
				for(i=0;i<n/2;i++){
					temp[i]=s[i];
				}
				delete[] s;
				s=temp;
				
				for(i=0; i<n; i++){
					s[i]=s[i-1];
				}
				cout<<"\nEnter Data of new Student: "<<endl;
				cout<<"Enter Student ID:"<<endl;
				cin>>s[0].id;
				cout<<"Enter Student First Name:"<<endl;
				cin>>s[0].first_name;
				cout<<"Enter Student Second Name:"<<endl;
				cin>>s[0].second_name;
				cout<<"Enter Student Gender:"<<endl;
				cin>>s[0].gender;
				cout<<"Enter Student D.O.B:"<<endl;
				cin>>s[0].dob;
				cout<<"Enter Student Address:"<<endl;
				cin>>s[0].address;
				cout<<"Enter Student City:"<<endl;
				cin>>s[0].city;
				cout<<"Enter Student Phone#:"<<endl;
				cin>>s[0].phone;
				cout<<"Enter Student Program:"<<endl;
				cin>>s[0].program;
				cout<<"Enter Student Year:"<<endl;
				cin>>s[0].year;
				index+=1;
			}
			else{
				for(i=index; i>0; i--){
					s[i]=s[i-1];
				}
				cout<<"\nEnter Data of new Student: "<<endl;
				cout<<"Enter Student ID:"<<endl;
				cin>>s[0].id;
				cout<<"Enter Student First Name:"<<endl;
				cin>>s[0].first_name;
				cout<<"Enter Student Second Name:"<<endl;
				cin>>s[0].second_name;
				cout<<"Enter Student Gender:"<<endl;
				cin>>s[0].gender;
				cout<<"Enter Student D.O.B:"<<endl;
				cin>>s[0].dob;
				cout<<"Enter Student Address:"<<endl;
				cin>>s[0].address;
				cout<<"Enter Student City:"<<endl;
				cin>>s[0].city;
				cout<<"Enter Student Phone#:"<<endl;
				cin>>s[0].phone;
				cout<<"Enter Student Program:"<<endl;
				cin>>s[0].program;
				cout<<"Enter Student Year:"<<endl;
				cin>>s[0].year;
				index+=1;
			}
		}
		else if(option==2){
			if(index==n){
				n=n*2;
				student *temp=new student[n];
				for(i=0;i<n/2;i++){
					temp[i]=s[i];
				}
				delete[] s;
				s=temp;
				cout<<"\nEnter Data of new Student: "<<endl;
				cout<<"Enter Student ID:"<<endl;
				cin>>s[index].id;
				cout<<"Enter Student First Name:"<<endl;
				cin>>s[index].first_name;
				cout<<"Enter Student Second Name:"<<endl;
				cin>>s[index].second_name;
				cout<<"Enter Student Gender:"<<endl;
				cin>>s[index].gender;
				cout<<"Enter Student D.O.B:"<<endl;
				cin>>s[index].dob;
				cout<<"Enter Student Address:"<<endl;
				cin>>s[index].address;
				cout<<"Enter Student City:"<<endl;
				cin>>s[index].city;
				cout<<"Enter Student Phone#:"<<endl;
				cin>>s[index].phone;
				cout<<"Enter Student Program:"<<endl;
				cin>>s[index].program;
				cout<<"Enter Student Year:"<<endl;
				cin>>s[index].year;
				index+=1;
			}
			else{
				cout<<"\nEnter Data of new Student: "<<endl;
				cout<<"Enter Student ID:"<<endl;
				cin>>s[index].id;
				cout<<"Enter Student First Name:"<<endl;
				cin>>s[index].first_name;
				cout<<"Enter Student Second Name:"<<endl;
				cin>>s[index].second_name;
				cout<<"Enter Student Gender:"<<endl;
				cin>>s[index].gender;
				cout<<"Enter Student D.O.B:"<<endl;
				cin>>s[index].dob;
				cout<<"Enter Student Address:"<<endl;
				cin>>s[index].address;
				cout<<"Enter Student City:"<<endl;
				cin>>s[index].city;
				cout<<"Enter Student Phone#:"<<endl;
				cin>>s[index].phone;
				cout<<"Enter Student Program:"<<endl;
				cin>>s[index].program;
				cout<<"Enter Student Year:"<<endl;
				cin>>s[index].year;
				index+=1;
			}
		}
}
//function to update student record
void update(student* s, int n, int index){
	string id;
	cout<<"\nEnter the Student Id you want to Update: "<<endl;
	cin>>id;
	for(i=0;i<n;i++){
		if(s[i].id==id){
			cout<<"\nUpdate Data of Student: "<<endl;
			cout<<"Enter Student ID:"<<endl;
			cin>>s[i].id;
			cout<<"Enter Student First Name:"<<endl;
			cin>>s[i].first_name;
			cout<<"Enter Student Second Name:"<<endl;
			cin>>s[i].second_name;
			cout<<"Enter Student Gender:"<<endl;
			cin>>s[i].gender;
			cout<<"Enter Student D.O.B:"<<endl;
			cin>>s[i].dob;
			cout<<"Enter Student Address:"<<endl;
			cin>>s[i].address;
			cout<<"Enter Student City:"<<endl;
			cin>>s[i].city;
			cout<<"Enter Student Phone#:"<<endl;
			cin>>s[i].phone;
			cout<<"Enter Student Program:"<<endl;
			cin>>s[i].program;
			cout<<"Enter Student Year:"<<endl;
			cin>>s[i].year;
			index+=1;
		}
		else{
			cout<<"Student with Id="<<id<<" doesn't exist in the list."<<endl;
		}
	}
}
//function to delete student record
void Delete(student* s, int n, int index){
	string id;
	cout<<"Enter the Student Id you want to Delete: "<<endl;
	cin>>id;
	for(i=0; i<n; i++){
		if(s[i].id==id){
			s[i]=s[i+1];
			index-=1;
		}
	}
}
//function to display student record on basis of Program Enrolled
void display(student* s, int n, int index){
	string p;
	cout<<"Enter Program for Data Display:"<<endl;
	cin>>p;
	for(i=0; i<n; i++){
		if(s[i].program==p){
			cout<<"\nThe Record of Students with Program="<<p<<" is:"<<endl;
			cout<<"Student ID:  "<<s[i].id<<endl;
			cout<<"Student Name:  "<<s[i].first_name<<" "<<s[i].second_name<<endl;
			cout<<"Student Gender:  "<<s[i].gender<<endl;
			cout<<"Student D.O.B:  "<<s[i].dob<<endl;
			cout<<"Student Address:  "<<s[i].address<<endl;
			cout<<"Student City:  "<<s[i].city<<endl;
			cout<<"Student Phone#:  "<<s[i].phone<<endl;
			cout<<"Student Program:  "<<s[i].program<<endl;
			cout<<"Student Year:  "<<s[i].year<<endl;
			cout<<" "<<endl;
		}
		else{
			cout<<"Student with Program="<<p<<" doesn't exist in the list."<<endl;
		}
	}
}
//function to display student record on basis of Admission Year
void displayYear(student* s, int n, int index){
	string y;
	cout<<"Enter Year for Data Display:"<<endl;
	cin>>y;
	for(i=0; i<n; i++){
		if(s[i].year==y){
			cout<<"\nThe Record of Students with Asmission Year="<<y<<" is:"<<endl;
			cout<<"Student ID:  "<<s[i].id<<endl;
			cout<<"Student Name:  "<<s[i].first_name<<" "<<s[i].second_name<<endl;
			cout<<"Student Gender:  "<<s[i].gender<<endl;
			cout<<"Student D.O.B:  "<<s[i].dob<<endl;
			cout<<"Student Address:  "<<s[i].address<<endl;
			cout<<"Student City:  "<<s[i].city<<endl;
			cout<<"Student Phone#:  "<<s[i].phone<<endl;
			cout<<"Student Program:  "<<s[i].program<<endl;
			cout<<"Student Year:  "<<s[i].year<<endl;
			cout<<" "<<endl;
		}
		else{
			cout<<"Students with Year="<<y<<" doesn't exist in the list."<<endl;
		}
	}
}
//function to search student record
void search(student* s, int n, int index){
	string id;
	cout<<"Enter Student Id you want to search"<<endl;
	cin>>id;
	for(i=0; i<n; i++){
		if(s[i].id==id){
			cout<<"The Record of Student with id="<<id<<" is:"<<endl;
			cout<<"Student ID:  "<<s[i].id<<endl;
			cout<<"Student Name:  "<<s[i].first_name<<" "<<s[i].second_name<<endl;
			cout<<"Student Gender:  "<<s[i].gender<<endl;
			cout<<"Student D.O.B:  "<<s[i].dob<<endl;
			cout<<"Student Address:  "<<s[i].address<<endl;
			cout<<"Student City:  "<<s[i].city<<endl;
			cout<<"Student Phone#:  "<<s[i].phone<<endl;
			cout<<"Student Program:  "<<s[i].program<<endl;
			cout<<"Student Year:  "<<s[i].year<<endl;
			cout<<" "<<endl;
			break;
		}
		else{
			cout<<"Student with id="<<id<<" doesn't exist in the list"<<endl;
		}
	}
}
//function to calculate memory required to store data of each student
void calculate(student* s, int n, int index){
	int size;
	cout<<"Total Memory Required to store data of each student is:"<<endl;
	for(i=0; i<n; i++){
			size=sizeof(s[i]);
			total+=size;
			cout<<"Memory required to store record of Student"<<i<<" ="<<total<<" bytes."<<endl;
		}
		cout<<"Total Memory Required is= "<<total<<endl;
}

**Comment by binish47** [comment]
okkk issue solved by beenish

**Comment by nomanmajeed** [comment]
Issues resolved. Thanks to git
